site_name: Cafe IS — Информационная система кафе
site_description: Документация проекта автоматизации кафе
site_author: Ваше Имя, Имя Напарника
theme: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Главная: index.md
  - Спецификация: specification.md
  - Архитектура: architecture.md
  - Use Cases: usecases.md
  - API:
      - Menu Service: api/menu.md
      - Order Service: api/order.md

plugins:
  - search